spring.config.import=optional:file:./.env[.properties]

spring.datasource.url=${DB_REFERENCE_URL:jdbc:postgresql://localhost:5432/restaurante2026_reference}
spring.datasource.username=${DB_REFERENCE_USERNAME:restaurante_app}
spring.datasource.password=${DB_REFERENCE_PASSWORD}

spring.main.web-application-type=none
spring.liquibase.enabled=false
spring.jpa.hibernate.ddl-auto=create
spring.jpa.open-in-view=false
